version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    command: "/bin/sh -c \"while sleep 1000; do :; done\""
    user: "${UID}:${GID}"
    volumes:
      - "../:/app"
