name: ci

on:
  push:
  pull_request:
    branches:
    - main
    - dev

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  tests:
    strategy:
      max-parallel: 4
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        copier-version:
        - "8.1.0"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set variables
        id: set_variables
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global init.defaultBranch main

      - name: Install dependencies
        run: python -m pip install -U copier

      - name: Setup tests (Unix)
        run: bash tests/setup.sh
        if: runner.os != 'Windows'

      - name: Run tests
        run: bash tests/test_generate.sh
        working-directory: ${{ github.workspace }}/tests/tmp
